CREATE SCHEMA IF NOT EXISTS connector;

CREATE TABLE IF NOT EXISTS connector.users (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS connector.edges (
    id SERIAL PRIMARY KEY,
    edge_id VARCHAR(255) NOT NULL UNIQUE,
    source VARCHAR(255) NOT NULL,
    target VARCHAR(255) NOT NULL,
    note text NOT NULL,
    type VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL UNIQUE,
)

CREATE TABLE IF NOT EXISTS connector.nodes (
    id SERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    position_x DOUBLE PRECISION NOT NULL,
    position_y DOUBLE PRECISION NOT NULL,
    style_height DOUBLE PRECISION NOT NULL,
    style_width DOUBLE PRECISION NOT NULL,
    note text NOT NULL,
    label text NOT NULL,
    type VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL UNIQUE,
)